### ISSUE TITLE
Split the `prioritize` feature in smaller parts

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/triagebot#615]
As of today, the prioritize feature has 3 roles:
- when the `@rustbot prioritize` is used, label the issue with the prioritization label
- when certain labels are added, label the issue with the prioritization label
- when the prioritization label is added, create a conversation on Zulip

I would propose to split those 3 features. This will allow for more flexibility, e.g. to define multiple triggers for auto-labeling. This is needed for the automation the Prioritization WG would like to set up in the near future:

> - Create a topic per stable/beta nominations, i-nominated and prs-waiting-on-team
> - Create a topic per P-critical and P-high regressions

I propose to have configuration like:

```toml
[prioritize]
label = "I-prioritize"

[autolabel."I-prioritize"]
trigger_labels = ["regression-from-stable-to-stable", "regression-from-stable-to-beta", "regression-from-stable-to-nightly"]
exclude_labels = [
    "P-*",
    "T-infra",
    "T-release",
]

[notify-zulip."I-prioritize"]
zulip_stream = 227806
topic = "I-prioritize #{number} {title}"
message_on_add = "@**WG-prioritization** issue #{number} has been requested for prioritization."
message_on_remove = "Issue #{number}'s prioritization request has been removed."
```

cc @Mark-Simulacrum @spastorino
